### ISSUE TITLE
[infra] https을 적용한다

### ISSUE THREAD

**Issue by hongbin-dev** [DDD-5/undertheriver-sgsg-backend#14]
## 작업내용
- https 적용한다.

## 이유
- HTTP 보안 및 추후진행할 OAuth의 디펜던시

## 안내사항
- 도메인, NGINX가 선행되어야함

**Comment by plzprayme** [comment]
HTTPS 적용했습니다.

certbot auto로 적용 했구요. api.sgsg.space , sgsg.space 둘 다 적용했고 갱신 cron job도 설정해놨습니다.

확인해보시고 추가 작업이 필요 없다고 판단되시면 이슈 닫아주세용~!
