### ISSUE TITLE
[feature] 로그인 redirect uri에 딥링크도 허용하도록 변경

### ISSUE THREAD

**Issue by hongbin-dev** [DDD-5/undertheriver-sgsg-backend#150]
## 추가하려는 기능 설명
- 현재 OAuth 로그인에서 딥링크를 허용하는지 알 수 없다. 확인하고 변경이 필요하다면 코드를 수정한다
- 허용된 URI에 딥링크를 추가한다

## 이유
- 

## 의존성
- 

## 안내사항
-

**Comment by plzprayme** [comment]
머지하신 것 같아서 클로즈합니다.
