### ISSUE TITLE
[bug] CORS 에러

### ISSUE THREAD

**Issue by plzprayme** [DDD-5/undertheriver-sgsg-backend#154]
## 버그내용
- CORS가 자꾸 발생합니다.

## 재현방법
- 정확하게 모르겠습니다.

### 의심 가는 것
1. URL에 특수문자를 허용하지 않아서. [(관련링크)](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=bb_&logNo=221384562529)
2. JWT 토큰이 만료된 후 접속 시 CORS 발생 
3. localhost 작업 시 CORS 발생

## 시도해본 것
- [X] URL에 특수문자 허용 (톰캣 설정)
- [ ] JWT 토큰 만료 시 CORS 발생 해결
- [ ] localhost 작업 시 CORS 발생 해결

**Comment by hongbin-dev** [comment]
#158
