### ISSUE TITLE
[feature] application.yml 추가

### ISSUE THREAD

**Issue by plzprayme** [DDD-5/undertheriver-sgsg-backend#29]
## 추가하려는 기능 설명
- h2-console, 디버깅 쿼리 출력 등을 하는 application.yml

## 이유
- 개발단계에서 필요한 프로퍼티 추가

## 의존성
- 

## 안내사항
- master에 올라갈 때는 삭제되어야 하거나 아예 devleop을 위한 profile을 추가하고 .gitignore에 추가하는 방식이 좋을듯합니다

**Comment by hongbin-dev** [comment]
일단... 추가된것같으니 닫겠습니다.
