### ISSUE TITLE
이슈템플릿 및 라벨을 생성한다

### ISSUE THREAD

**Issue by khb1109** [DDD-5/undertheriver-sgsg-backend#4]

**Comment by khb1109** [comment]
![image](https://user-images.githubusercontent.com/33685054/111902167-5830b980-8a7f-11eb-8841-58a0b06dccac.png)

@plzprayme 성찬님 위 사진처럼 라벨 만들었습니다.
이슈나 PR에서 라벨붙여주시면 가시성 좋을 것 같아요.

추가하면 좋을라벨이나, 색상변경하면 좋을 것 말씀해주시면 감사하겠습니다. (유지보수같은 라벨도 있으면 좋겠네요)

**Comment by plzprayme** [comment]
지금 보기에는 딱히 추가할 라벨이 떠오르지 않네요.
일단 close하고 라벨을 더 추가 해야 할 때 다시 open 하겠습니다
